version: "3.7"

services:
  front-end:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - target: 80
        published: 80
    networks:
      - react-antd-todo-network

networks:
  react-antd-todo-network:
    driver: bridge
